steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        './Dockerfile',
        '-t',
        'asia.gcr.io/$PROJECT_ID/spin-wheel-rust:$TAG_NAME',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/spin-wheel-rust:$TAG_NAME']

tags: ['latest', '$TAG_NAME']
options:
  machineType: 'E2_HIGHCPU_8'
