version: "3.3"
services:
  db:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "spin_wheel"
      POSTGRES_PASSWORD: "adminpostgres"
    image: postgres:12.3-alpine
    ports:
      - "5455:5455"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spin-whell:latest
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - DATABASE_URL= "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    