-- Your SQL goes here
create type PRIZES_CATEGORIES as enum('cash','gift');
create table tb_spin_prizes(
      id int primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1  START 1 CACHE 1 NO CYCLE),
      prize_weight int not null,
      prize_name varchar not null,
      prize_note varchar,
      prize_category PRIZES_CATEGORIES default null,  
      prize_amount int
);