-- Your SQL goes here
create table tb_spin_promos(
     id int8 primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
     promo_amount int,
     code_user varchar not null,
     company_code varchar not null,
     expired_at Timestamp,
     point_currention_time Timestamp,
     created_at Timestamp,
     updated_at Timestamp,
     created_by varchar,
     updated_by varchar   
);